mkdir build
cd build
cmake -G Ninja ../llvm -DLLVM_ENABLE_PROJECTS="mlir;lld;llvm;clang"    -DLLVM_BUILD_EXAMPLES=ON    -DLLVM_TARGETS_TO_BUILD="X86;AMDGPU"    -DCMAKE_BUILD_TYPE=Debug    -DLLVM_ENABLE_ASSERTIONS=ON    -DBUILD_SHARED_LIBS=ON    -DLLVM_BUILD_LLVM_DYLIB=ON    -DMLIR_ROCM_RUNNER_ENABLED=1    -DMLIR_MIOPEN_DRIVER_ENABLED=1    -DMLIR_ENABLE_SQLITE=1 -DMLIR_LETAO_DRIVER_ENABLED=1
cmake --build . --target check-mlir
